seed: 42

# --------------------------------
# Dataset
# --------------------------------
dataset_path: /kaggle/input/datasets/ashfakazadnafi/brats2021-tar/ASNR-MICCAI-BraTS2023-PED-Challenge-TrainingData/ASNR-MICCAI-BraTS2023-PED-Challenge-TrainingData
modalities:
  - t1n
  - t1c
  - t2w
  - t2f

num_input_slices: 5

image_size: 128

num_classes: 4

train_split: 0.8

# --------------------------------
# Hardware
# --------------------------------

device: cuda

num_workers: 2

use_amp: true

# --------------------------------
# Training
# --------------------------------

batch_size: 4

epochs: 60

learning_rate: 0.00005

weight_decay: 0.00001

# --------------------------------
# Transfer Learning
# --------------------------------

pretrained_weights: pretrained_weights/ssl_encoder.pth

freeze_encoder: false

# --------------------------------
# Output Directories
# --------------------------------

save_dir: /kaggle/working/outputs/checkpoints/
log_dir: /kaggle/working/outputs/logs/
visualization_dir: /kaggle/working/outputs/visualizations/

# --------------------------------
# Checkpoints
# --------------------------------

checkpoint_path: /kaggle/working/outputs/checkpoints/segmentation_checkpoint.pth

best_model_path: /kaggle/working/outputs/checkpoints/best_segmentation_model.pth